import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/client/Header";
import "./globals.css";
import styles from '@/styles/HomePage.module.css'
import { MantineProvider } from "@mantine/core";

const geistSans = Geist( {
  variable: "--font-geist-sans",
  subsets: [ "latin" ],
} );

const geistMono = Geist_Mono( {
  variable: "--font-geist-mono",
  subsets: [ "latin" ],
} );

export const metadata: Metadata = {
  title: "TrustWorthy",
  description: "Generated by create next app",
};

export default function RootLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> )
{
  return (
    <html lang="en">
      <body className={ `${geistSans.variable} ${geistMono.variable} antialiased` }>
        <MantineProvider>
        <div className= {styles.homepage}>
          <Header />
          <main className="flex-1 ">
            { children }
          </main>
        </div>
        </MantineProvider>
      </body>
    </html>
  );
}