"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  AppShell,
  Container,
  createTheme,
  MantineProvider
} from "@mantine/core";
import "@mantine/core/styles.css";
import "./globals.css";
import classes from './layout.module.css';
import AppNavbar from "@/components/layout/AppNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const myTheme = createTheme({
  defaultRadius: 0,
  fontSmoothing: true,
  fontFamily: "Roboto, sans-serif",
  primaryColor: "gray",
  components: {
    Select: {
      defaultProps: {
        size: "xs",
      },
    },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MantineProvider theme={myTheme}>
          <AppShell withBorder={false}>
            <Container size="75%" style={{ height: "100%", paddingLeft: "80px", paddingTop: "30px" }}>
              <div className={classes.customNavbar}>
                {/* <div className={classes.navbarContent}>
                  <AppNavbar />
                </div> */}
              </div>
              {children}
            </Container>
          </AppShell>
        </MantineProvider>
      </body>
    </html>
  );
}