import styles from '@/styles/HomePage.module.css';
import { AppShell, createTheme, MantineProvider } from "@mantine/core";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/client/Header";
import "@mantine/core/styles.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TrustWorthy",
  description: "Generated by create next app",
};

const myTheme = createTheme({
  defaultRadius: 0,
  fontSmoothing: true,
  fontFamily: "Roboto, sans-serif",
  primaryColor: "gray",
  components: {
    Select: {
      defaultProps: {
        size: "xs",
        labelProps: {
          style: { color: "white" },
        },
      },
    },
    Text: {
      defaultProps: {
        c: "white",
      },
    },
    Title: {
      defaultProps: {
        c: "white",
      }
    }
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MantineProvider theme={myTheme}>
          <AppShell withBorder={false}>
            <div className={styles.homepage}>
              <Header />
              <main>
                {children}
              </main>
            </div>
          </AppShell>
        </MantineProvider>
      </body>
    </html>
  );
}